source: docs
url: https://wesellis.github.io/CBR-to-CBZ-Converter
title: Comic Cruncher & Combiner
description: Professional dual-mode comic processing suite with parallel optimization and TPB collection creation
